# Generated by Django 5.2 on 2025-05-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailing_owner_mailingrecipient_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingrecipient',
            options={'permissions': [('can_view_all_recipients', 'Может просматривать всех получателей')]},
        ),
    ]
