# Generated by Django 5.2 on 2025-05-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailingrecipient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_all_mailing', 'Может просматривать все рассылки')]},
        ),
    ]
