# Generated by Django 5.2 on 2025-05-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_mailing_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
    ]
