# Generated by Django 5.2 on 2025-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_remove_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_all_mailing', 'Может просматривать все рассылки'), ('can_disable_mailing', 'Может отключать рассылки')]},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена'), ('disabled', 'Отключена')], default='created', max_length=10, verbose_name='Статус'),
        ),
    ]
